server:
  port: 8000

webHookPath: https://2968-89-109-48-77.eu.ngrok.io

bot:
  name: anime_nyaa_bot
  token: ${token_anime_bot}
#  owner:

#db related settings
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/animebot
    username: root
    password: 15v09o19v99a
    driver-class-name: com.mysql.cj.jdbc.Driver